### ISSUE TITLE
ARS-Workshop Issues

### ISSUE THREAD

**Issue by ianmilligan1** [ianmilligan1/hackathon#1]
If you run into trouble with the [ARS-Workshop](https://github.com/vinaygoel/ars-workshop), please use this thread for community troubleshooting and help.

**Comment by sylvainrocheleau** [comment]
I went through the workshop. Everything worked OK except for Exercise-2 where Option-1 terminated with success but I was unable to retrieve data. Option-2 worked fine. Anyone got the same problem?
